# Generated by Django 3.2.25 on 2026-04-09 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_name', models.CharField(max_length=254)),
                ('suggested_category', models.CharField(blank=True, max_length=254)),
                ('description', models.TextField()),
                ('reason', models.TextField(blank=True)),
                ('reference_url', models.URLField(blank=True, max_length=1024)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Suggestion',
                'verbose_name_plural': 'Product Suggestions',
                'ordering': ['-created_on'],
            },
        ),
    ]
